### PR TITLE
Added delete test for Mirror.

### PR DESCRIPTION
**Pull request by jaspreetw**
Added delete mirror test case. 
Removed non needed test_create_mirror method from create snapshot, snaphot tag and mirror set test cases.

### CODE REVIEW

**Comment by sorenisanerd** [comment]
@jaspreetw This seems to fail every once in a while. Have you seen this,  too?

**Comment by jaspreetw** [comment]
@sorenh I noticed this  yesterday. Some tests failed in one build but without any code change those test cases ran successfully in the next test run .

**Comment by sorenisanerd** [comment]
@jaspreetw Ok. Can you try tracking it down, please? We need these tests to be reliable.

**Comment by jaspreetw** [comment]
Sure I will track down the issue, however I can't reproduce yesterday's failure.  
Yesterday's Issue was fixed after fixing pep8 Error.

**Pull request merged**
