### PR TITLE
WIP Added functional test_signup

### PR DESCRIPTION
**Pull request by mayankkapoor**
Functional test opens signup page and signs up, logs in.
This may be a good PR to start the conversation on creating functional tests for package builder.

### CODE REVIEW

**Comment by mayankkapoor** [comment]
I'm unsure why the travis build failed. Both my local tests and circleCI tests passed. Don't think there is a problem with the code.

**Comment by sorenisanerd** [comment]
A couple of comments:

FWIW, I consider the Django based web UI "legacy". I'm happy to keep it around if it's useful, but aasemble.com will feature an AngularJS based UI that uses the API.

Selenium based tests sound like a good idea. I don't know for sure, but I think the reason it's not working on Travis CI is because there's not DISPLAY set. Travis has documention on how to get this working: http://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI

That page also talks about Sauce Labs, but I don't think you need that. I think that's just for situations where you want to test against many, many different user agents. Travis-CI says it has firefox in all its environments, so that should suffice.

**Comment by sorenisanerd** [comment]
Just to be clear, this needs to work on Travis before I can merge it, otherwise test results from there will be useless.

**Comment by sorenisanerd** [comment]
I've made Django 1.9 compatibility optional by ignoring those failures from Travis. We still run them so we can track the effort, but seeing as allauth doesn't work with Django 1.9 anyway yet, there's no much point in chasing it ourselves.

If you merge with master or rebase this branch, the Django 1.9 tests should be informational only.

Just FYI, you don't need to create a new branch and a new PR to do this, you can just merge or rebase and push to the same branch. In case of a rebase, you just use "git push --force".

**Comment by mayankkapoor** [comment]
Closing PR as submitting changes in another PR.

**Pull request closed without merging**
